<?php
$galleries = $block->getImageGallery();
?>
<?php if ($galleries->getSize()): ?>
    <div class="owl-carousel owl-theme brand-slider">
        <?php foreach ($galleries as $gallery): ?>
            <div class="item">
                <?php if ($gallery->getImageUrl()): ?>
                    <a class="image-galery gallery-popup" href="<?= $gallery->getImageUrl(); ?>" title="<?= $gallery->getTitle(); ?>">
                <?php endif; ?>
                <img src="<?= $gallery->getImageUrl(); ?>" alt="<?= $gallery->getTitle(); ?>" width="100%"/>
                <?php if ($gallery->getImageUrl()): ?>
                    </a>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
    <script type="text/javascript">
        require(['jquery', 'owlcarousel','jquery/jquery-ui','Neo_Gallery/js/magnific-popup'], function($) {
            $('.brand-slider').owlCarousel({
                loop: true,
                margin: 30,
                nav: true,
                navText : ["",""],
                dots: false,
                responsive:{
                    0:{
                        items:1,
                        nav:true
                    },
                    600:{
                        items:3,
                        nav:true
                    },
                    1000:{
                        items:3,
                        nav:true,
                        loop:false
                    }
                }
            });
        });
    </script>
<?php endif; ?>